SHELL:=/bin/bash
PACKAGE_NAME:=armasec_core
ROOT_DIR:=$(shell dirname $(shell pwd))

install:
	poetry install

test: install
	poetry run pytest

mypy: install
	poetry run mypy ${PACKAGE_NAME} --pretty

lint: install
	poetry run ruff check ${PACKAGE_NAME} tests

qa: test mypy lint
	echo "All quality checks pass!"

format: install
	poetry run ruff format ${PACKAGE_NAME} tests
	poetry run ruff check --fix ${PACKAGE_NAME} tests

clean:
	@find . -iname '*.pyc' -delete
	@find . -iname '*.pyo' -delete
	@find . -iname '*~' -delete
	@find . -iname '*.swp' -delete
	@find . -iname '__pycache__' -delete
	@rm -r .mypy_cache
	@rm -r .pytest_cache
	@find . -name '*.egg' -print0|xargs -0 rm -rf --
	@rm -rf .eggs/
	@rm -fr build/
	@rm -fr dist/
	@rm -fr *.egg-info
